### ISSUE TITLE
Authentication config label doesn't work

### ISSUE THREAD

**Issue by TurtleKwitty** [shizunge/gantry#64] opened 2024-10-10 09:06 UTC
I have a configs file point at by the GANTRY_REGISTRY_CONFIGS_FILE with the necessary info, in the logs it says that login succeeded so this part should be correct and I have confirmed manually logging in with the credentials also works.

The problem is with using the auth; I have the ``gantry.auth.config=<config-name>`` label on my service but when Gantry attempts to update it gives the following error: ``Image <image> does not exist or it is not available. ERROR: failed to authorize: failed to fetch anonymous token: unexpected status from GET request to <registry url>: 401 Unauthorized``. I have turned up logging to DEBUG level but it does not give any additional information. There are no configs found in ``docker config ls`` which seems abnormal since the readme says Gantry creates some. 

I am out of ideas what could possibly be wrong and thinking it may well be a bug; there is not much that could even be wrong at all, I have checked the config name matches, I have checked if it gives any additional errors with a wrong name that doesn't appear in the configs file (it does not, I would have hoped it would to confirm) nor does it log what config it thinks it should be using.

**Comment by TurtleKwitty** [comment] 2024-10-10 20:21
Strange that docker config is correctly not showing gantry configs then since the documentation of docker says it should be swarm aware and even the swarm configs link shows using docker config to be correct. It might be a good idea to mention what is the correct way to verify gantry configs that are mentioned in the readme? 

Using manifest command had the same result sadly, the login is successful but for some reason it errors with 401 unauthed still. The none command does work, not my favorite solution but when it works it works I guess. It would be great for the debug level to give more details, or possibly a verbose log level if you want the debug messages to stay fairly sparse

**Comment by shizunge** [comment] 2024-10-10 20:33
1. Yes. we need to document the difference. "docker config" is not the correct cmd to read these information. Actually I cannot follow you comments.

2. The Configuration file is some files in the file system. If you run Gantry in docker, you can only access them inside the container. If you run Gantry as a script, you can access them at the host file system.

3. We need to try to reproduce this in a small test. The tests are at `tests/gantry_login_spec.sh`, but I think the change need to go to the setup at `tests/spec_gantry_test_helper.sh`, where we need to enforce the login for these tests, which is missing today. I pasted the doc for the registry here for further reference.  https://distribution.github.io/distribution/about/configuration/#auth

**Comment by shizunge** [comment] 2024-11-05 17:59
I cannot reproduce the problem you had. I have created new tests that indicate reading image succeed with logging in and failed without logging. The registry is using basic auth and the docker server version is 26 API 1.45.

You do not share the entire log so I don't know what was happenning.
Here are a few guesses.

## configuration name mismatch
 
The configuration ID on the service (via `gantry.auth.config`) mismatched the one you set via `GANTRY_REGISTRY_CONFIG*`. This one generates similar log you had, though it is not exactly the same.

The test `test_login_config_mismatch` said 
```
[2024-11-05T09:03:20+00:00][fv-az1435-534][ERROR] test_login_config_mismatch worker0: Image 127.0.0.1:55028/gantry/test:login_negative-1730797387-2373-4zh2zsy4 does not exist or it is not available. Docker buildx returns: ERROR: pull access denied, repository does not exist or may require authorization: authorization failed: no basic auth credentials 
```

To eliminate this possibility, you need to check the logging message and adding `--config` message have the same ID. as shown in the example below

> ```
> [2024-11-05T09:03:19+00:00][fv-az1435-534][INFO] test_login_config_mismatch: Logged into registry 127.0.0.1:55028 with configuration C1730797387-2373-wbvhxtp8. WARNING! Your password will be stored unencrypted in C1730797387-2373-wbvhxtp8/config.json. Configure a credential helper to remove this warning. See https://docs.docker.com/engine/reference/commandline/login/#credentials-store  Login Succeeded 
> ```
> 
> ```
> [2024-11-05T09:03:20+00:00][fv-az1435-534][DEBUG] test_login_config_mismatch worker0: Adding options "--config C1730797387-2373-wbvhxtp8-incorrect" to docker commands for gantry-test-1730797387-2373-9ssb1cbo. 
> ```

The latest development version adds a warning when the configuration file is not found.

For your reference, I paste the entire log of the test `test_login_config_mismatch` here.

```
[2024-11-05T09:03:19+00:00] Loading libraries from /home/runner/work/gantry/gantry/src
[2024-11-05T09:03:19+00:00][DEBUG] test_login_config_mismatch: Set NODE_NAME=fv-az1435-534 
[2024-11-05T09:03:19+00:00][fv-az1435-534][INFO] test_login_config_mismatch: Run on Docker host fv-az1435-534. Docker version client 26.1.3 (API 1.45) server 26.1.3 (API 1.45) 
[2024-11-05T09:03:19+00:00][fv-az1435-534][INFO] test_login_config_mismatch: Starting. 
[2024-11-05T09:03:19+00:00][fv-az1435-534][DEBUG] test_login_config_mismatch: Created STATIC_VARIABLES_FOLDER /tmp/tmp.wljNdRxVOs 
[2024-11-05T09:03:19+00:00][fv-az1435-534][INFO] test_login_config_mismatch: Logged into registry 127.0.0.1:55028 with configuration C1730797387-2373-wbvhxtp8. WARNING! Your password will be stored unencrypted in C1730797387-2373-wbvhxtp8/config.json. Configure a credential helper to remove this warning. See https://docs.docker.com/engine/reference/commandline/login/#credentials-store  Login Succeeded 
[2024-11-05T09:03:19+00:00][fv-az1435-534][INFO] test_login_config_mismatch: Before updating, Docker Hub rate remains 86. 
[2024-11-05T09:03:19+00:00][fv-az1435-534][DEBUG] test_login_config_mismatch: SERVICES_EXCLUDED_FILTERS=label=gantry.services.excluded=true 
[2024-11-05T09:03:19+00:00][fv-az1435-534][DEBUG] test_login_config_mismatch: SERVICES_FILTERS=name=gantry-test-1730797387-2373-9ssb1cbo 
[2024-11-05T09:03:20+00:00][fv-az1435-534][INFO] test_login_config_mismatch: Starting updating. 
[2024-11-05T09:03:20+00:00][fv-az1435-534][INFO] test_login_config_mismatch: Inspecting 1 service(s). 
[2024-11-05T09:03:20+00:00][fv-az1435-534][DEBUG] test_login_config_mismatch: Run 1 _inspect_service in parallel. 
[2024-11-05T09:03:20+00:00][fv-az1435-534][WARN] test_login_config_mismatch worker0: C1730797387-2373-wbvhxtp8-incorrect is not a directory that contains Docker configuration files. 
[2024-11-05T09:03:20+00:00][fv-az1435-534][WARN] test_login_config_mismatch worker0: There are 1 configuration(s) set via GANTRY_REGISTRY_CONFIG* or GANTRY_REGISTRY_CONFIGS_FILE: 
[2024-11-05T09:03:20+00:00][fv-az1435-534][WARN] test_login_config_mismatch worker0: - C1730797387-2373-wbvhxtp8 
[2024-11-05T09:03:20+00:00][fv-az1435-534][DEBUG] test_login_config_mismatch worker0: Adding options "--config C1730797387-2373-wbvhxtp8-incorrect" to docker commands for gantry-test-1730797387-2373-9ssb1cbo. 
[2024-11-05T09:03:20+00:00][fv-az1435-534][ERROR] test_login_config_mismatch worker0: Image 127.0.0.1:55028/gantry/test:login_negative-1730797387-2373-4zh2zsy4 does not exist or it is not available. Docker buildx returns: ERROR: pull access denied, repository does not exist or may require authorization: authorization failed: no basic auth credentials 
[2024-11-05T09:03:20+00:00][fv-az1435-534][DEBUG] test_login_config_mismatch worker0: Skip updating gantry-test-1730797387-2373-9ssb1cbo because there is a failure to obtain the manifest from the registry of image 127.0.0.1:55028/gantry/test:login_negative-1730797387-2373-4zh2zsy4. 
[2024-11-05T09:03:20+00:00][fv-az1435-534][ERROR] test_login_config_mismatch: Failed to inspect 1 service(s): 
[2024-11-05T09:03:20+00:00][fv-az1435-534][ERROR] test_login_config_mismatch: - gantry-test-1730797387-2373-9ssb1cbo 
[2024-11-05T09:03:20+00:00][fv-az1435-534][DEBUG] test_login_config_mismatch: Run 1 _update_single_service in parallel. 
[2024-11-05T09:03:21+00:00][fv-az1435-534][INFO] test_login_config_mismatch: After updating, Docker Hub rate remains 85. Used rate 1. 
[2024-11-05T09:03:21+00:00][fv-az1435-534][INFO] test_login_config_mismatch: No images to remove. 
[2024-11-05T09:03:21+00:00][fv-az1435-534][INFO] test_login_config_mismatch: No services updated. 
[2024-11-05T09:03:21+00:00][fv-az1435-534][ERROR] test_login_config_mismatch: 1 service(s) update failed: 
[2024-11-05T09:03:21+00:00][fv-az1435-534][ERROR] test_login_config_mismatch: - gantry-test-1730797387-2373-9ssb1cbo 
[2024-11-05T09:03:21+00:00][fv-az1435-534][DEBUG] test_login_config_mismatch notify: Skip sending notification via Apprise. 
[2024-11-05T09:03:21+00:00][fv-az1435-534][DEBUG] test_login_config_mismatch: Removing STATIC_VARIABLES_FOLDER /tmp/tmp.wljNdRxVOs 
[2024-11-05T09:03:21+00:00][fv-az1435-534][ERROR] test_login_config_mismatch: Done. Use 0m 2s. 1 error(s). 
```

## Registry does not support reading image manifest

`docker buildx imagetools inspect` and `docker manifest inspect` might not work your registry.

To eliminate this possibility, run the commands manually.

```
docker --config my-test-config login <registry>
docker --config my-test-config buildx imagetools inspect <registry>/<image>
docker --config my-test-config manifest inspect <registry>/<image>
rm -r my-test-config 
```

Note that the tests I wrote only tested basic auth.

## Docker API version

I am not sure it makes a difference. The docker version used by the tests is Docker version client 26.1.3 (API 1.45) server 26.1.3 (API 1.45) .

**Comment by shizunge** [comment] 2024-11-14 06:13
I finally found the bug.

# Root cause and fix

The root cause is a combination of the following issues.
* In some function we used an incorrect variable. We should use a local variable, instead we use a global variable.
* The global variable was accidentally set in another function. It was used as a for-loop variable. The variable was not marked as local.

```
my_function_1() {
  # We are missing: local my_variable_1=
  # Therefore my_variable_1 become a global variable.
  for my_variable_1 in ${list}; do
  done
}

my_function_2() {
  local my_variable_2="${1}"
  # We used the incorrect variable here, we should use my_variable_2
  # I was expecting my_variable_1 will be empty string, which will trigger the test failure.
  # However combining two issues, my_variable_1 is a global variable and non-empty.
  # Therefore it masked the error in the test.
  some_function "${my_variable_1}"
}
```

We fixed the root causes:

* Use the correct local variable in the corresponding function.
* Mark all for-loop variables local. This should prevent similar error in the future.

# Why tests do not catch the error

To trigger this error, both of the following must be true.

* There are more than 1 services to update.
* `gantry.auth.config` is missing on the last service (sort by name).

While testing, we usually only test a single feature, like multiple service or login. We did not test the combination of two features yet.

# Release

A fix was checked into the development branch. I need to add more tests and to improve the documents before making a new release. The expected release data would be late Nov or Dec 2024.

# Workaround

While waiting for release, you can use one of the following workarounds.

##  If you only login to a single registry.
Use
* GANTRY_REGISTRY_HOST (in needed)
* GANTRY_REGISTRY_PASSWORD
* GANTRY_REGISTRY_USER

Do not use
* GANTRY_REGISTRY_CONFIG
* `gantry.auth.config` on services.

Gantry will login using the [default docker configuration](https://docs.docker.com/reference/cli/docker/#configuration-files).

## If you don't login to the same host with different user names.

I believe docker CLI allows you to login into multiple host with a single configuration file. (For example, you can login to multiple host using the default configuration.) We can take advantage of this.

* Use the same auth config name for all authentications.
* Set `gantry.auth.config` to all services.

This does not work if you need to login to the same host with different user names for different services.

# Recommend
Following the suggestion in this [comment](https://github.com/shizunge/gantry/issues/64#issuecomment-2457836239), a complete log would be very helpful in debugging this issue. The problem falls under "configuration name mismatch" section,  where we might see some expected messages missing from the log.
To help diagnose the root cause, I recommend uploading the complete log file.

**Comment by shizunge** [comment] 2024-11-15 05:00
I created a new release. It should fix the problem.
`docker pull ghcr.io/shizunge/gantry:2024.1114.0`

**Closed by shizunge** 2024-11-15 05:00 UTC
Labels: bug

**Comment by TurtleKwitty** [comment] 2024-11-15 18:54
Oh wow thanks for continuing to look into this, work has been hectic so I hadnt had time to look past things working when manual but will test this new release
